version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dev_api_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db 
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
